version: "3.7"
services:
  marquez_web:
    # image: coinfirm/marquez-web:latest
    image: coinfirm/marquez-web:0.7.0-coinfirm-v1
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000
    ports:
      - "3000:3000"
    depends_on:
      - marquez

  # seed_marquez_db:
  #   build: ./docker/db
  #   environment:
  #     - MARQUEZ_HOST=marquez
  #     - MARQUEZ_PORT=5000
  #     - MARQUEZ_ADMIN_PORT=5001
  #   volumes:
  #     - ./docker/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
  #   depends_on:
  #     - marquez
  #   entrypoint: ["./wait-for-it.sh", "marquez:5000", "--", "./entrypoint.sh"]

  marquez:
    # image: coinfirm/marquez:latest
    image: coinfirm/marquez:0.11.3-coinfirm-v1
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - MARQUEZ_PORT=5000
      - MARQUEZ_ADMIN_PORT=5001
      - MARQUEZ_CONFIG=/usr/src/app/marquez.yml
      - POSTGRES_HOST=marquez_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=marquez
      - POSTGRES_USER=marquez
      - POSTGRES_PASSWORD=marquez
      - LOG_LEVEL=DEBUG
    volumes:
      - ./docker/wait-for-it.sh:/usr/src/app/wait-for-it.sh
      - ./docker/marquez.yml:/usr/src/app/marquez.yml
    depends_on:
      - marquez_db
    entrypoint: ["./wait-for-it.sh", "marquez_db:5432", "--", "./entrypoint.sh"]

  marquez_db:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MARQUEZ_DB=marquez
      - MARQUEZ_USER=marquez
      - MARQUEZ_PASSWORD=marquez
    volumes:
      - ./docker/db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - marquez-postgres-dev:/var/lib/postgresql/data # Persistent volume for DEV
volumes:
  marquez-postgres-dev: # Persistent volume for DEV